function lgraph = build_network(gamma,k,isCRNet,cfg)

inputSize = [cfg.Nt cfg.Ndt 2];

decodeChannels = 16;

decodeSize = cfg.Nt * cfg.Ndt * decodeChannels;

inputLayer = imageInputLayer( ...
    inputSize, ...
    'Name','input', ...
    'Normalization','none');

encoderLayers = [
    convolution2dLayer(3,32, ...
        'Padding','same', ...
        'Name','conv_enc_1')

    reluLayer('Name','relu_enc_1')

    convolution2dLayer(3,32, ...
        'Padding','same', ...
        'Name','conv_enc_2')

    reluLayer('Name','relu_enc_2')

    convolution2dLayer(3,16, ...
        'Padding','same', ...
        'Name','conv_enc_3')

    reluLayer('Name','relu_enc_3')

    flattenLayer('Name','flatten')

    fullyConnectedLayer(k, ...
        'Name','latent')
    ];

decoderLayers = [
    fullyConnectedLayer(decodeSize, ...
        'Name','fc_decode')

    functionLayer( ...
        @(X) vectorToImageFunction( ...
        X,cfg.Nt,cfg.Ndt,decodeChannels), ...
        'Formattable',true, ...
        'Name','reshape')

    convolution2dLayer(3,32, ...
        'Padding','same', ...
        'Name','conv_dec_1')

    reluLayer('Name','relu_dec_1')

    convolution2dLayer(3,32, ...
        'Padding','same', ...
        'Name','conv_dec_2')

    reluLayer('Name','relu_dec_2')

    convolution2dLayer(3,16, ...
        'Padding','same', ...
        'Name','conv_dec_3')

    reluLayer('Name','relu_dec_3')
    ];

reconstructionMain = convolution2dLayer( ...
    1,2, ...
    'Padding','same', ...
    'Name','reconstruction_main');

outputLayer = convolution2dLayer( ...
    1,2, ...
    'Padding','same', ...
    'Name','output');

lgraph = layerGraph();

lgraph = addLayers(lgraph,inputLayer);

lgraph = addLayers(lgraph,encoderLayers);

lgraph = addLayers(lgraph,decoderLayers);

lgraph = addLayers(lgraph,reconstructionMain);

lgraph = addLayers(lgraph,outputLayer);

lgraph = connectLayers( ...
    lgraph, ...
    'input', ...
    'conv_enc_1');

lgraph = connectLayers( ...
    lgraph, ...
    'latent', ...
    'fc_decode');

lgraph = connectLayers( ...
    lgraph, ...
    'relu_dec_3', ...
    'reconstruction_main');

if isCRNet

    residualLayers = [
        convolution2dLayer(3,16, ...
            'Padding','same', ...
            'Name','residual_conv_1')

        reluLayer('Name','residual_relu')

        convolution2dLayer(1,2, ...
            'Padding','same', ...
            'Name','residual_conv_2')
        ];

    fusion = additionLayer(2,'Name','fusion');

    lgraph = addLayers(lgraph,residualLayers);

    lgraph = addLayers(lgraph,fusion);

    lgraph = connectLayers( ...
        lgraph, ...
        'relu_dec_3', ...
        'residual_conv_1');

    lgraph = connectLayers( ...
        lgraph, ...
        'reconstruction_main', ...
        'fusion/in1');

    lgraph = connectLayers( ...
        lgraph, ...
        'residual_conv_2', ...
        'fusion/in2');

    lgraph = connectLayers( ...
        lgraph, ...
        'fusion', ...
        'output');

else

    lgraph = connectLayers( ...
        lgraph, ...
        'reconstruction_main', ...
        'output');

end

end


function Z = vectorToImageFunction(X,Nt,Ndt,nChannels)

expectedSize = Nt * Ndt * nChannels;

s = size(X);

if s(1) ~= expectedSize
    error('Invalid decoder vector size.');
end

Z = reshape( ...
    X, ...
    Nt, ...
    Ndt, ...
    nChannels, ...
    []);

Z = dlarray(stripdims(Z),'SSCB');

end
